# Tên của workflow, sẽ hiển thị trong tab "Actions"
name: Node.js App Workflow

# Workflow này sẽ được kích hoạt khi có code được đẩy lên branch "main"
# Hoặc có thể được chạy thủ công từ tab "Actions"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # Tên của job, bạn có thể đặt tùy ý
  build-and-run:
    # Chạy trên một máy ảo Ubuntu mới nhất do GitHub cung cấp
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Thiết lập môi trường Node.js phiên bản 22
      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Bước 2: Cập nhật và cài đặt các công cụ cần thiết (chỉ cần git)
      - name: Install Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git

      # Bước 3: Clone repository chứa ứng dụng
      - name: Clone application repository
        run: git clone https://github.com/hlounhdepzai/tool

      # Bước 4: Chạy ứng dụng từ bên trong thư mục đã clone
      - name: Run the Node.js application
        # Đặt thư mục làm việc cho bước này là 'tool'
        working-directory: ./tool
        run: |
          # Cấp quyền thực thi cho các file
          chmod +x *
          # Chạy ứng dụng
          node app.js

